name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: mcamimejia
          token: ${{ secrets.SONAR_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/banksofka-frontend:${{ github.sha }} .
      
      - name: Tag Docker Image
        run: |
          docker tag ghcr.io/${{ github.repository }}/banksofka-frontend:${{ github.sha }} ghcr.io/${{ github.repository }}/banksofka-frontend:v1.0.0
          docker tag ghcr.io/${{ github.repository }}/banksofka-frontend:${{ github.sha }} ghcr.io/${{ github.repository }}/banksofka-frontend:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/banksofka-frontend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/banksofka-frontend:v1.0.0
          docker push ghcr.io/${{ github.repository }}/banksofka-frontend:latest