name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
          
      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/tulio-rangel/banksofka-frontend:${{ github.sha }} .
      
      - name: Tag Docker Image
        run: |
          docker tag ghcr.io/tulio-rangel/banksofka-frontend:${{ github.sha }} ghcr.io/tulio-rangel/banksofka-frontend:${{ github.ref_name }}
          docker tag ghcr.io/tulio-rangel/banksofka-frontend:${{ github.sha }} ghcr.io/tulio-rangel/banksofka-frontend:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/tulio-rangel/banksofka-frontend:${{ github.sha }}
          docker push ghcr.io/tulio-rangel/banksofka-frontend:v1.0.0
          docker push ghcr.io/tulio-rangel/banksofka-frontend:latest
